[project]
name = "perception"
version = "0.1.0"
description = "Main repository for perception team code"
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "numpy>=2.3.4",
    "plyfile>=1.1.3",
    "torch>=2.9.0",
]
